### PR TITLE
Add support for UUID and Either

### PR DESCRIPTION
**Pull request by LMnet**
Add support for `UUID` and `Either` types.

### CODE REVIEW

**Comment by cvogt** [comment]
@LMnet Nice stuff :). Could I kindly ask you to sign our small and simple CLA? https://cla-assistant.io/xdotai/diff?pullRequest=14

**Comment by cvogt** [comment]
(don't worry about the merge conflict btw, I'll take care of that)

**Comment by LMnet** [comment]
@cvogt Signed.

**Comment by cvogt** [comment]
@LMnet awesome. I built on top of your commit here: #16 So I am closing this and getting #16 ready to be merged. Will release 1.2.0 shortly after, probably later this week.

**Pull request closed without merging**
